<<<<<<< HEAD
# Generated by Django 6.0.3 on 2026-05-12 07:07
=======
# Generated by Django 6.0.2 on 2026-05-12 07:09
>>>>>>> a65c2fa4bdc7183cd5a579fd2d49a3fb6f3c6eda

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='drainagelocation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='maintenancereport',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
